"""empty message

Revision ID: 17c5096f6c10
Revises: 5447990ccb67
Create Date: 2015-10-19 15:09:31.437575

"""

# revision identifiers, used by Alembic.
revision = '17c5096f6c10'
down_revision = '5447990ccb67'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('link', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'link')
    ### end Alembic commands ###
