"""empty message

Revision ID: 1e5abed6a40c
Revises: 73163fa3389
Create Date: 2015-10-20 21:30:00.143450

"""

# revision identifiers, used by Alembic.
revision = '1e5abed6a40c'
down_revision = '73163fa3389'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strats', sa.Column('difficulty', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strats', 'difficulty')
    ### end Alembic commands ###
