"""empty message

Revision ID: 2966302b61cc
Revises: 17c5096f6c10
Create Date: 2015-10-20 18:23:54.654103

"""

# revision identifiers, used by Alembic.
revision = '2966302b61cc'
down_revision = '17c5096f6c10'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('flags', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'flags')
    ### end Alembic commands ###
