"""empty message

Revision ID: 50e007366a3e
Revises: 1e5abed6a40c
Create Date: 2015-10-20 22:50:26.105286

"""

# revision identifiers, used by Alembic.
revision = '50e007366a3e'
down_revision = '1e5abed6a40c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('short_name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'short_name')
    ### end Alembic commands ###
