"""empty message

Revision ID: 5447990ccb67
Revises: 25e7d9d9bf30
Create Date: 2015-10-19 15:05:49.447320

"""

# revision identifiers, used by Alembic.
revision = '5447990ccb67'
down_revision = '25e7d9d9bf30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.area_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.add_column(u'strats', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'strats', 'rooms', ['room_id'], ['room_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strats', type_='foreignkey')
    op.drop_column(u'strats', 'room_id')
    op.drop_table('rooms')
    ### end Alembic commands ###
