"""empty message

Revision ID: 73163fa3389
Revises: 2966302b61cc
Create Date: 2015-10-20 19:28:32.280474

"""

# revision identifiers, used by Alembic.
revision = '73163fa3389'
down_revision = '2966302b61cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strats', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'strats', 'games', ['game_id'], ['game_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strats', type_='foreignkey')
    op.drop_column('strats', 'game_id')
    ### end Alembic commands ###
